name: Update cms/master

on:
  push:
    branches:
      - staging

jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: aitgab/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'staging'
          target: 'uat'
